##### Admin CMS APIs

### root api
GET http://localhost:8000/

### Create new user
POST  http://localhost:8000/api/v1/user
Content-Type: application/json

{
  "fname": "Prem",
  "lname": "Acharya",
  "email": "a@a.com",
  "dob": "2021-10-10",
  "password": "12345678",
  "phone": "041000000",
  "address" : "Sydne , NSW",
  "gender": "male"
  

}
 

### verify admin email
PATCH   http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
  "pin": "731977",
  "email": "bsssc1f@ba.com"
}

### Login user
POST   http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
  "email": "a@a.com",
  "password": "12345678"
}


#################### category router
### get all or single categories
GET  http://localhost:8000/api/v1/category/
 
 
### Post new category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
  "name": "Furniture",
  "parentCat": null
}

### update category
PATCH http://localhost:8000/api/v1/category
Content-Type: application/json

{
  "_id": "61452d86816786f35bf3a163",
  "name": "Furnitures",
  "parentCat": null
}


### Delete category
DELETE   http://localhost:8000/api/v1/category/61452aadf990131366c010f3

# Electronic
# => Monile
# => Monitors

# Accessories

# Grocery
#=> Meat
# => Milk

